import Image from 'next/image'
import Head from 'next/head'

import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Archit Rathod</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Homemade+Apple&family=Satisfy&family=Ubuntu:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <Main />

      <About />

      <Skills />

      <Projects />

      <Contact />

    </div>
  )
}
